# Generated by Django 3.2.1 on 2021-06-16 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_productfeatures_productfeaturesvalidators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeaturesvalidators',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productfeaturesvalidators',
            name='feature',
        ),
        migrations.DeleteModel(
            name='ProductFeatures',
        ),
        migrations.DeleteModel(
            name='ProductFeaturesValidators',
        ),
    ]
