# Generated by Django 3.2.1 on 2021-06-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurevalidator',
            name='valid_feature_value',
            field=models.CharField(max_length=100, verbose_name='Валидное значение'),
        ),
    ]
